apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-ingress-to-web
  namespace: web
spec:
  podSelector: {} 
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - {} 
